### ISSUE TITLE
segfault on 32 bit?

### ISSUE THREAD

**Issue by JinnCirce** [luciusmagn/sic#1] opened 2018-02-06 20:36 UTC
just throwing it out there, that it seems to segfault under 32 bits, unlike the original, (and even thypon's colour version works fine...)
I can view the version, but nothing else, as far as I've tried, compilation only warns of \e being nonstandard (same with thypon's version) and executing results in "segmentation fault"...

**Comment by luciusmagn** [comment] 2018-02-06 20:48
Hmm, I did very little to change it apart from adding colours, logging and customizing config. What compiler, libc and system are you using? I will also check if I have the latest version committed, chances are I don't

**Comment by JinnCirce** [comment] 2018-02-07 05:55
libc reports "stable release version 2.12"
and using the default cc (though changing to gcc didn't change a thing)
(arch is i686)

**Comment by JinnCirce** [comment] 2018-02-07 19:47
seems still to be broken when made under 32, fine as always under 64 bits...
btw, what is `FILE* log = fopen("/home/sic/log", "a");` doing in sic.c?

**Comment by luciusmagn** [comment] 2018-02-07 23:36
Hmm, I will try installing a 32-bit toolchain to test it, then. I use the
file to keep track of message  history. The path is hardcoded because I
didn't think anyone else would try to use it :D

2018-02-07 20:47 GMT+01:00 jan69 <notifications@github.com>:

**Comment by JinnCirce** [comment] 2018-02-08 10:30
there's no real need for me to use it, but still...would be nice to have on a remote server in case I need it, I could just use the other coloured version as well...

**Comment by luciusmagn** [comment] 2018-02-09 20:57
Hmm, I built my sic on 32bits and it works as intended. Odd. I am using GCC 7.3.0 w/ glibc on Arch. What is your exact configuration? The information you gave me 3 days ago doesn't seem to indicate any problem

**Comment by JinnCirce** [comment] 2018-02-21 21:01
my bad, on closer look it's centos6.8...so wrong call, but still broken...as you might see from the ~2 weeks delay, I've given up on this specific version....

**Comment by luciusmagn** [comment] 2018-02-22 07:42
No worries, I am not sure what causes the problem, but if the other version works, you are probably better off using that instead :smile:

**Closed as completed** 2018-02-23 15:52 UTC
